import "./globals.scss";
import { Open_Sans } from "next/font/google";
import styles from "./layout.module.scss";
import cn from "classnames";

const openSans = Open_Sans({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(openSans.className, styles.body)}>{children}</body>
    </html>
  );
}
